name: health_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# ... (Версія та environment залишаються без змін)
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_dotenv: ^5.1.0

  flutter_localizations:
    sdk: flutter

  # Firebase packages
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.13.5
  firebase_storage: ^11.5.6
  table_calendar: ^3.1.2
  intl: 0.20.2
  fl_chart: ^0.66.0
  url_launcher: ^6.2.0
  # Image handling
  image_picker: ^1.0.4


  # Local DB
  sqflite: ^2.3.0
  path_provider: ^2.1.1

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # 🚀 Активація локальних асетів (ЗМІНА ТУТ!)
  # Це дозволить додатку бачити вашу папку assets/images/
  assets:
    - assets/avatars/
    - assets/doctor_avatars/
    - .env